services:

  db:
    image: postgres:17

    container_name: postgres_db

    environment:
      POSTGRES_DB: backend_saas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .

    container_name: backend_saas

    ports:
      - "8000:8000"

    depends_on:
      - db

    env_file:
      - .env
    #environment:
      #DATABASE_URL: postgresql+psycopg://postgres:admin@db:5432/backend_saas
      # postgresql://postgres:admin@db:5432/saas_db
      #SECRET_KEY: super_secret_jwt_key_2026

      #ALGORITHM:  HS256

      #ACCESS_TOKEN_EXPIRE_MINUTES: 30

volumes:
  postgres_data: